# Generated by Django 4.2.8 on 2026-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(blank=True, max_length=255, null=True)),
                ('market_address', models.CharField(blank=True, max_length=255)),
                ('market_orientation', models.CharField(blank=True, max_length=255)),
                ('market_work_time', models.CharField(blank=True, max_length=150, null=True)),
                ('market_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('market_grill', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_work_time', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_day_off', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_one_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_one_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_one_work_time', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_one_day_off', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_two_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_two_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_two_work_time', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_two_day_off', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_three_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_three_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_three_work_time', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_three_day_off', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('market_format', models.CharField(choices=[('Korzinka', 'Корзинка'), ('Korzinka Mahalla', 'Корзинка Махалля'), ('Korzinka Diskont', 'Корзинка Дисконт'), ('FLO', 'ФЛО'), ('REDTAG', 'РЕДТАГ')], default='Korzinka', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
