# Generated by Django 5.1.2 on 2024-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255)),
                ('market_work_time', models.CharField(max_length=50)),
                ('market_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('market_grill', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_full_name', models.CharField(max_length=255)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_work_time', models.CharField(max_length=50)),
                ('manager_day_off', models.CharField(max_length=50)),
                ('supervisor_one_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_one_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_one_work_time', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_one_day_off', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_two_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_two_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supervisor_two_work_time', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_two_day_off', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
