# Generated by Django 5.1.2 on 2024-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='market_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='market',
            name='market_orientation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='market',
            name='supervisor_three_day_off',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='supervisor_three_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='supervisor_three_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='supervisor_three_work_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
