# Generated by Django 5.1.2 on 2024-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_market_address_market_market_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='market_format',
            field=models.CharField(choices=[('Korzinka', 'Корзинка'), ('Korzinka Mahalla', 'Корзинка Махалля'), ('Korzinka Diskont', 'Корзинка Дисконт'), ('FLO', 'ФЛО'), ('REDTAG', 'РЕДТАГ')], default='Korzinka', max_length=50),
        ),
        migrations.AddField(
            model_name='market',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
