# Generated by Django 5.1.2 on 2024-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_alter_market_market_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market_work_time',
            field=models.CharField(max_length=150),
        ),
    ]
